### ISSUE TITLE
Cannot default property to null / undefined without setting type

### ISSUE THREAD

**Issue by m-mujica** [canjs/can-observable-mixin#148]
Defining an element like this:

```js
class MyElement extends StacheElement {
  static get view() {
    return "<p>hello</p>";
  }

  static get props() {
    return {
      thisIsNull: { default: null },
      thisIsUndefined: { default: undefined }
    };
  }
}
```

causes the following line to throw an error https://github.com/canjs/can-observable-mixin/blob/fa5a085a9bed861175adc63f5dc7d230b584807c/src/define.js#L880.

A workaround is to add a type like `thisIsNull: { default: null, type: type.maybe(String) }`.

**What should `can-observable-mixin` set `type` to if the default value is null / undefined?**

**Comment by phillipskevin** [comment]
I think we should just prevent this error so that it is basically a `type.Any`.
