### ISSUE TITLE
"Hungry" types

### ISSUE THREAD

**Issue by matthewp** [canjs/can-observable-mixin#45]
In the past CanJS typed objects such as `CanMap`, `DefineMap`, and `DefineList` would always eagerly convert objects into observables. For example when you do:

```js
let map = new DefineMap({a: {b: 'c'}});
```

Then `map.a` is also a DefineMap, and is therefore observable.

This changes with `DefineObject`, `DefineArray` and anything else that uses their mixins, like `StacheDefineElement`. These objects *do not* convert inner values. So:

```js
let props = {a: {b: 'c'}};
let obj = new DefineObject(props);

obj.a === props.a;
```

This is good in a lot of ways; it helps with performance and prevents attempting to convert objects that you want left alone.

However there are still cases where you would want this sort of recursive observable conversion. So we've created a new type that can be used like so:

```js
import { DefineObject, type, DeepObservableObjectOrArray } from "can";

class Favorites extends DefineObject {
  static define = {
    options: type.convert(DeepObservableObjectOrArray)
  }
}

new DefineObject({ options: {a: {b: 'c'}} });
```

## What to name it

We need help because we're unsure of what to call this. Some options for consideration with brief explanations:

* __Eager__: It eagerly converts objects to observables.
* __Greedy__: Like a greedy regex.
* __RecursiveObservable__: It recursively converts to observables.
* __ToDefineObjectOrArray__: This is more direct in what it does, which is convert to DefineObjects, DefineArrays, or leaves alone if primitive types.
* __BuiltInOrObservable__: Also direct but less wordy.
* __Hungry__: A type that is *hungry*, it eats objects and digests them into observables.

**Comment by justinbmeyer** [comment]
```
GreedyObject {
	propertyDefaults: Greedy
}
GreedyArray {
	items: Greedy
}

function Greedy(){
	
}
Greedy[can.new] = function(value){
	if(isPlainArray) {
		return new GreedyArray(value);
	} 
	else if(isPlainObject) {
		return new GreedyArray(value);
	} else {
		return value
	}
}
```

**Comment by justinbmeyer** [comment]
```js
Classroom extends DefineObject {

	static define = {
		students: {type: ToDefineObjectOrArray} 
		ToObservableOrAny
		students: ConvertToObservableOrAny,

		students: 
			type.union(
				type.convert(DefineObject),
				type.convert(DefineArray),
				type.any
			)
	}
}
```

**Comment by matthewp** [comment]
This is in major.
